### ISSUE TITLE
Can't load libtorrent DLL

### ISSUE THREAD

**Issue by MirkoCovizzi** [AlexCovizzi/torrenttv#12]
After running `run.py` I get the following traceback:

```
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from torrenttv.webapi.app import App
  File "C:\Users\Mirko\Desktop\OpenSource\torrenttv\torrenttv\webapi\__init__.py", line 1, in <module>
    from .app import App
  File "C:\Users\Mirko\Desktop\OpenSource\torrenttv\torrenttv\webapi\app.py", line 5, in <module>
    from torrenttv.bittorrent import Session
  File "C:\Users\Mirko\Desktop\OpenSource\torrenttv\torrenttv\bittorrent\__init__.py", line 1, in <module>
    from .session import Session
  File "C:\Users\Mirko\Desktop\OpenSource\torrenttv\torrenttv\bittorrent\session.py", line 2, in <module>
    from python_libtorrent import libtorrent as lt  # pylint: disable=no-name-in-module
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by AlexCovizzi** [comment]
Related to #8
